apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-engine-config
data:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_HOST: reporting-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: reporting
  TYPEORM_LOGGING: "false"
  JWT_EXPIRATION: 4h

